#!/usr/bin/env bash

export GIT_WORK_TREE=..
git checkout -f HEAD

repo_dir=$(git rev-parse --show-toplevel)
repo_name=$(basename "$repo_dir")

if [ "$repo_name" = "nixos-config" ]; then
    echo "Repository is nixos-config, running home-manager switch..."
    home-manager switch --flake $repo_dir &
    echo "hm switch running"
fi